const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const header=$("#header"), menu=$(".mobile-menu"), menuButton=$(".menu-button");
addEventListener("scroll",()=>header.classList.toggle("scrolled",scrollY>30),{passive:true});
function toggleMenu(open){menu.classList.toggle("open",open);menu.setAttribute("aria-hidden",String(!open));menuButton.setAttribute("aria-expanded",String(open));document.body.style.overflow=open?"hidden":""}
menuButton.onclick=()=>toggleMenu(true); $(".menu-close").onclick=()=>toggleMenu(false); $$(".mobile-menu a").forEach(a=>a.onclick=()=>toggleMenu(false)); addEventListener("keydown",e=>e.key==="Escape"&&toggleMenu(false));
$("#year").textContent=new Date().getFullYear();
$$('.select-package').forEach(button=>button.onclick=()=>{const name=button.closest('[data-package]').dataset.package;$("#package-field").value=name;$("#contacto").scrollIntoView({behavior:"smooth"})});
const form=$("#lead-form"), status=$(".form-status");
form.addEventListener("submit",async e=>{e.preventDefault();if(form.website.value)return;const button=$("button[type=submit]",form);button.disabled=true;status.textContent="Enviando…";const data=Object.fromEntries(new FormData(form));delete data.website;const cfg=window.ADFER_CONFIG||{};
  if(!cfg.SUPABASE_URL?.startsWith("https://")||cfg.SUPABASE_ANON_KEY?.startsWith("PEGA_")){status.textContent="Falta conectar Supabase en config.js.";button.disabled=false;return}
  try{const response=await fetch(`${cfg.SUPABASE_URL}/rest/v1/prospectos`,{method:"POST",headers:{apikey:cfg.SUPABASE_ANON_KEY,Authorization:`Bearer ${cfg.SUPABASE_ANON_KEY}`,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify(data)});if(!response.ok)throw new Error(await response.text());form.reset();status.textContent="Gracias. Recibimos tus datos y nos pondremos en contacto."}catch(err){console.error(err);status.textContent="No pudimos enviar tus datos. Escríbenos por WhatsApp o inténtalo nuevamente."}finally{button.disabled=false}
});
const observer=new IntersectionObserver(entries=>entries.forEach(x=>x.isIntersecting&&x.target.classList.add("visible")),{threshold:.12});$$('section article,.intro,.steps').forEach(x=>observer.observe(x));
const scenes=$$('[data-scene]'),currentLabel=$('[data-slide-current]');let sceneIndex=0,sceneTimer;
function showScene(next){sceneIndex=(next+scenes.length)%scenes.length;scenes.forEach((scene,index)=>scene.classList.toggle('active',index===sceneIndex));if(currentLabel)currentLabel.textContent=String(sceneIndex+1).padStart(2,'0')}
function startScenes(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;clearInterval(sceneTimer);sceneTimer=setInterval(()=>showScene(sceneIndex+1),6000)}
$('[data-slide-prev]')?.addEventListener('click',()=>{showScene(sceneIndex-1);startScenes()});$('[data-slide-next]')?.addEventListener('click',()=>{showScene(sceneIndex+1);startScenes()});
const heroArt=$('.hero-art');heroArt?.addEventListener('mouseenter',()=>clearInterval(sceneTimer));heroArt?.addEventListener('mouseleave',startScenes);
if(heroArt&&!matchMedia('(prefers-reduced-motion: reduce)').matches){heroArt.addEventListener('pointermove',event=>{const box=heroArt.getBoundingClientRect(),x=(event.clientX-box.left)/box.width-.5,y=(event.clientY-box.top)/box.height-.5;heroArt.style.setProperty('--rx',`${-y*5}deg`);heroArt.style.setProperty('--ry',`${x*7}deg`)});heroArt.addEventListener('pointerleave',()=>{heroArt.style.setProperty('--rx','0deg');heroArt.style.setProperty('--ry','0deg')})}
startScenes();
const caseGallery=$('[data-case-gallery]'),caseSlides=$$('[data-case-slide]'),caseCurrent=$('[data-case-current]'),caseProgress=$('[data-case-progress]');let caseIndex=0,caseTimer;
function selectCase(index,behavior='smooth'){if(!caseGallery||!caseSlides.length)return;caseIndex=(index+caseSlides.length)%caseSlides.length;caseSlides.forEach((slide,i)=>slide.classList.toggle('active',i===caseIndex));const active=caseSlides[caseIndex];caseGallery.scrollTo({left:active.offsetLeft-(caseGallery.clientWidth-active.offsetWidth)/2,behavior});if(caseCurrent)caseCurrent.textContent=String(caseIndex+1).padStart(2,'0');if(caseProgress)caseProgress.style.width=`${((caseIndex+1)/caseSlides.length)*100}%`}
function startCase(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;clearInterval(caseTimer);caseTimer=setInterval(()=>selectCase(caseIndex+1),6500)}
$('[data-case-prev]')?.addEventListener('click',()=>{selectCase(caseIndex-1);startCase()});$('[data-case-next]')?.addEventListener('click',()=>{selectCase(caseIndex+1);startCase()});caseGallery?.addEventListener('mouseenter',()=>clearInterval(caseTimer));caseGallery?.addEventListener('mouseleave',startCase);caseGallery?.addEventListener('keydown',event=>{if(event.key==='ArrowRight'){event.preventDefault();selectCase(caseIndex+1);startCase()}if(event.key==='ArrowLeft'){event.preventDefault();selectCase(caseIndex-1);startCase()}});
let caseScrollTimer;caseGallery?.addEventListener('scroll',()=>{clearTimeout(caseScrollTimer);caseScrollTimer=setTimeout(()=>{const center=caseGallery.scrollLeft+caseGallery.clientWidth/2;let nearest=0,distance=Infinity;caseSlides.forEach((slide,i)=>{const delta=Math.abs(slide.offsetLeft+slide.offsetWidth/2-center);if(delta<distance){distance=delta;nearest=i}});if(nearest!==caseIndex)selectCase(nearest,'auto')},120)},{passive:true});
const lightbox=$('[data-case-lightbox]');$$('.case-zoom').forEach(button=>button.addEventListener('click',()=>{const image=$('img',button),caption=button.closest('figure')?.querySelector('figcaption b')?.textContent||'';const target=$('img',lightbox);target.src=image.src;target.alt=image.alt;$('p',lightbox).textContent=caption;lightbox.showModal()}));$('[data-lightbox-close]')?.addEventListener('click',()=>lightbox.close());lightbox?.addEventListener('click',event=>{if(event.target===lightbox)lightbox.close()});
selectCase(0,'auto');startCase();
