create table if not exists public.prospectos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  empresa text not null,
  telefono text not null,
  correo text not null,
  ciudad text not null,
  servicio text not null,
  paquete text,
  objetivo text not null,
  mensaje text,
  creado_en timestamptz not null default now()
);

alter table public.prospectos enable row level security;

drop policy if exists "permitir prospectos anonimos" on public.prospectos;

create policy "permitir prospectos anonimos"
on public.prospectos
for insert
to anon
with check (
  char_length(nombre) between 2 and 120
  and char_length(telefono) between 7 and 30
  and char_length(correo) between 5 and 180
);

revoke select, update, delete on public.prospectos from anon;
grant insert on public.prospectos to anon;
grant usage, select on sequence public.prospectos_id_seq to anon;
