"use client";

import { useEffect, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowDownRight, ArrowRight, BarChart3, Camera, Check, ChevronDown, Menu, MessageCircle, Minus, MousePointer2, Play, Plus, Send, Sparkles, Target, Users, X, Zap } from "lucide-react";
import { siteContent, type PackageId } from "@/data/site-content";
import { track } from "@/lib/analytics";
import { whatsappUrl } from "@/lib/whatsapp";

const primaryWhatsApp = whatsappUrl("6142562234", "Hola AdFer Marketing, me interesa conocer una propuesta para mi marca.");
const reveal = { initial: { opacity: 0, y: 28 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-80px" }, transition: { duration: .6, ease: [0.22, 1, 0.36, 1] as const } };
const Logo = ({ light = false }: { light?: boolean }) => <a className={`logo ${light ? "light" : ""}`} href="#inicio" aria-label="AdFer Marketing, inicio"><span>AD</span>FER<small>MARKETING</small></a>;

function Header() {
  const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false);
  useEffect(() => { const fn = () => setScrolled(scrollY > 30); fn(); addEventListener("scroll", fn, { passive: true }); return () => removeEventListener("scroll", fn); }, []);
  useEffect(() => { document.body.style.overflow = open ? "hidden" : ""; const esc = (e: KeyboardEvent) => e.key === "Escape" && setOpen(false); addEventListener("keydown", esc); return () => { document.body.style.overflow = ""; removeEventListener("keydown", esc); }; }, [open]);
  return <header className={`header ${scrolled ? "scrolled" : ""}`}><div className="nav-shell"><Logo light={!scrolled}/><nav aria-label="Navegación principal">{siteContent.nav.map(([label, href]) => <a key={href} href={href}>{label}</a>)}</nav><a href="#contacto" className="btn nav-cta">Solicitar propuesta</a><button className="menu-button" onClick={() => setOpen(true)} aria-label="Abrir menú" aria-expanded={open}><Menu/></button></div>
  <AnimatePresence>{open && <motion.div className="mobile-menu" initial={{ clipPath: "circle(0% at 90% 5%)" }} animate={{ clipPath: "circle(150% at 90% 5%)" }} exit={{ clipPath: "circle(0% at 90% 5%)" }}><button onClick={() => setOpen(false)} aria-label="Cerrar menú"><X/></button><Logo light/><div className="mobile-links">{siteContent.nav.map(([label, href], i) => <a key={href} href={href} onClick={() => setOpen(false)}><small>0{i+1}</small>{label}</a>)}</div><a className="btn yellow" href={primaryWhatsApp}>WhatsApp <ArrowRight/></a><p>@adfer_marketing · Chihuahua, MX</p></motion.div>}</AnimatePresence></header>;
}

function Hero() { const reduce = useReducedMotion(); return <section className="hero" id="inicio"><div className="hero-noise"/><div className="container hero-grid"><motion.div className="hero-copy" initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.7}}><p className="eyebrow">{siteContent.hero.eyebrow}</p><h1>Convertimos atención digital en <em>crecimiento real.</em></h1><p className="hero-text">{siteContent.hero.text}</p><div className="hero-actions"><a className="btn yellow" href="#contacto" onClick={()=>track("hero_cta_click")}>Solicitar propuesta <ArrowRight/></a><a className="text-link" href="#paquetes">Conocer paquetes <ArrowDownRight/></a></div><div className="indicators">{siteContent.hero.indicators.map(x=><span key={x}><Check/> {x}</span>)}</div></motion.div>
  <div className="hero-art" aria-label="Composición visual de contenido y métricas"><motion.div className="social-card" animate={reduce?{}:{y:[0,-10,0],rotate:[-3,-1,-3]}} transition={{duration:7,repeat:Infinity}}><div className="social-top"><span className="avatar">A</span><b>adfer_marketing</b><span>•••</span></div><div className="post-art"><span>IDEAS QUE<br/><strong>CONECTAN</strong></span><Sparkles/></div><div className="social-bottom"><Camera/><MessageCircle/><Send/></div></motion.div><motion.div className="metric-card" animate={reduce?{}:{y:[0,8,0],rotate:[4,2,4]}} transition={{duration:8,repeat:Infinity}}><small>META ADS · PANEL</small><b>Alcance → Conversión</b><div className="bars"><i/><i/><i/><i/><i/></div><span><Zap/> Campaña activa</span></motion.div><div className="reel-card"><Play/><small>REEL / 00:12</small><div className="timeline"><i/></div></div><div className="float-badge"><Users/><Camera/></div><MousePointer2 className="cursor-art"/></div></div></section> }

function Marquee(){return <div className="marquee" aria-hidden="true"><div>{Array(3).fill("ESTRATEGIA · CONTENIDO · PUBLICIDAD · DISEÑO · MÉTRICAS · CRECIMIENTO · ").join("")}</div></div>}
function Manifesto(){const pillars=[["Creatividad que atrapa","Ideas con una forma visual memorable.",Sparkles],["Tecnología que conecta","Herramientas al servicio de cada interacción.",Zap],["Análisis que mejora","Decisiones guiadas por señales útiles.",BarChart3]];return <section className="manifesto section"><div className="container"><div className="editorial-intro"><motion.h2 {...reveal}>No publicamos<br/>por publicar.</motion.h2><motion.p {...reveal}>Combinamos creatividad que atrapa, tecnología que conecta y análisis que ayuda a mejorar cada decisión.</motion.p></div><div className="pillars">{pillars.map(([title,text,Icon],i)=><motion.article key={String(title)} {...reveal}><b>0{i+1}</b><h3>{String(title)}</h3><p>{String(text)}</p>{typeof Icon !== "string" && <Icon/>}</motion.article>)}</div></div></section>}
function Services(){return <section id="servicios" className="section services"><div className="container"><p className="kicker">LO QUE HACEMOS</p><motion.h2 {...reveal}>Creatividad con<br/><span>intención comercial.</span></motion.h2><div className="bento">{siteContent.services.map((s,i)=><motion.article {...reveal} className={s.featured?"service-card featured":"service-card"} key={s.title}><span className="card-index">0{i+1}</span><div>{s.featured&&<Target/>}<h3>{s.title}</h3><p>{s.text}</p></div>{s.featured?<><div className="abstract-chart"><i/><i/><i/><i/></div><a href="#contacto">Activar una campaña <ArrowRight/></a></>:<ArrowDownRight/>}</motion.article>)}</div></div></section>}
function Process(){return <section id="proceso" className="section process"><div className="container"><p className="kicker">MÉTODO ADFER</p><motion.h2 {...reveal}>De la idea a una<br/>estrategia que trabaja.</motion.h2><div className="timeline-process">{siteContent.process.map(([title,text],i)=><motion.article {...reveal} key={title}><div className="node">0{i+1}</div><div><h3>{title}</h3><p>{text}</p></div></motion.article>)}</div></div></section>}
function CaseStudy(){const c=siteContent.caseStudy; return <section id="resultados" className="section case" onMouseEnter={()=>track("case_study_view")}><div className="container"><p className="kicker light">CASO DE ÉXITO</p><motion.h2 {...reveal}>Sí, sí… mucho hablar.<br/><em>Pero también tenemos resultados.</em></motion.h2><div className="case-grid"><div><p className="case-client">{c.client}<span>{c.specialty}</span></p>{[["EL RETO",c.challenge],["LA ESTRATEGIA",c.strategy],["LOS RESULTADOS",c.result]].map(([t,x])=><article key={t}><b>{t}</b><p>{x}</p></article>)}</div><div className="case-collage">{["Captura de estadísticas","Diseño de contenido","Alcance orgánico","Alcance con pauta"].map((x,i)=><div key={x} className={`placeholder p${i+1}`}><span>{i<2?"01":"02"}</span><BarChart3/><b>{x}</b><small>ESPACIO EDITABLE</small></div>)}</div></div></div></section>}

function Pricing({onSelect}:{onSelect:(id:PackageId)=>void}){return <section id="paquetes" className="section pricing"><div className="container"><p className="kicker">INVERSIÓN MENSUAL</p><motion.h2 {...reveal}>¿Te interesa?<br/><span>Conoce nuestros paquetes.</span></motion.h2><div className="price-grid">{siteContent.packages.map((p,i)=><motion.article {...reveal} className={`price-card ${p.id}`} key={p.id}>{p.badge&&<div className="popular">{p.badge}</div>}<div className="vertical-label">{p.label}</div><div className="price-head"><p>{p.description}</p><h3>{p.price}<small> MXN<br/>/ mensuales</small></h3></div><ul>{p.features.map(f=><li key={f}><Check/>{f}</li>)}</ul><button className="btn" onClick={()=>onSelect(p.id)}>Elegir {p.label.toLowerCase()} <ArrowRight/></button></motion.article>)}</div><PricingComparison/></div></section>}
function PricingComparison(){const [tab,setTab]=useState<PackageId>("intermediate");const selected=siteContent.packages.find(p=>p.id===tab)!;return <div className="comparison"><h3>Compara sin complicarte.</h3><div className="compare-tabs">{siteContent.packages.map(p=><button className={tab===p.id?"active":""} onClick={()=>setTab(p.id)} key={p.id}>{p.label}</button>)}</div><div className="compare-mobile"><h4>{selected.price} MXN</h4>{selected.features.map(f=><p key={f}><Check/>{f}</p>)}</div><div className="compare-table"><div><b>Incluye</b>{siteContent.packages.map(p=><b key={p.id}>{p.label}</b>)}</div>{["Publicaciones","Reels","Meta Ads","Reporte mensual","Pruebas A/B"].map((f,i)=><div key={f}><span>{f}</span>{siteContent.packages.map((p,pi)=><span key={p.id}>{i===0?[8,12,16][pi]:i===1?[3,6,8][pi]:i===2?["1 campaña","2 campañas","Avanzada"][pi]:i===3?(pi>0?<Check/>:"—"):pi===2?<Check/>:"—"}</span>)}</div>)}</div></div>}
function FAQ(){const [open,setOpen]=useState(0);return <section className="section faq"><div className="container faq-grid"><div><p className="kicker">ANTES DE EMPEZAR</p><h2>Preguntas<br/>frecuentes.</h2></div><div>{siteContent.faqs.map(([q,a],i)=>{const active=open===i;return <article key={q}><button onClick={()=>{setOpen(active?-1:i);track("faq_open",{question:q})}} aria-expanded={active}><span>0{i+1}</span><b>{q}</b>{active?<Minus/>:<Plus/>}</button><AnimatePresence initial={false}>{active&&<motion.p initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}}>{a}</motion.p>}</AnimatePresence></article>})}</div></div></section>}
function FinalCTA(){return <section className="final-cta"><div className="orb one"/><div className="orb two"/><div className="container"><p>¿TENEMOS UN TRATO?</p><h2>Cuéntanos qué necesita tu marca y construyamos una estrategia a su medida.</h2><div><a className="btn dark" href="#contacto">Hablar con AdFer Marketing <ArrowRight/></a><a className="btn outline" href="#paquetes">Ver paquetes</a></div></div></section>}
function Contact({pkg}:{pkg:PackageId|""}){const [status,setStatus]=useState<"idle"|"loading"|"success">("idle"); const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();if(status==="loading")return;setStatus("loading");track("contact_form_submit",{package:pkg});const form=e.currentTarget;fetch("/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(new FormData(form) as unknown as Record<string,string>).toString()}).then(()=>setStatus("success")).catch(()=>setStatus("idle"))};return <section id="contacto" className="section contact"><div className="container contact-grid"><div><p className="kicker light">HABLEMOS</p><h2>Tu siguiente etapa empieza con una conversación.</h2><p>Cuéntanos dónde está tu marca y hacia dónde quieres llevarla.</p><div className="contact-list"><b>Medios digitales</b>{siteContent.contacts.digital.map(([n,p])=><a key={p} href={whatsappUrl(p,"Hola, me interesa una propuesta de AdFer Marketing.")}><span>{n}</span>{p.replace(/(\d{3})(\d{3})(\d{4})/,'$1 $2 $3')}<MessageCircle/></a>)}<b>Ventas</b>{siteContent.contacts.sales.map(([n,p])=><a key={p} href={`tel:+52${p}`}><span>{n}</span>{p.replace(/(\d{3})(\d{3})(\d{4})/,'$1 $2 $3')}<ArrowRight/></a>)}</div></div><form name="contacto" method="POST" data-netlify="true" data-netlify-honeypot="website" onSubmit={submit} onFocus={()=>track("contact_form_start")}><input type="hidden" name="form-name" value="contacto"/><div className="honeypot" aria-hidden="true"><label>Sitio web<input name="website" tabIndex={-1} autoComplete="off"/></label></div>{[["Nombre","text","name"],["Empresa","text","company"],["Teléfono","tel","phone"],["Correo","email","email"],["Ciudad","text","city"]].map(([l,t,n])=><label key={n}>{l}<input required name={n} type={t} placeholder={l}/></label>)}<label>Servicio de interés<select required name="service" defaultValue=""><option value="" disabled>Selecciona un servicio</option>{siteContent.services.map(s=><option key={s.title}>{s.title}</option>)}</select><ChevronDown/></label><label>Paquete<select name="package" value={pkg} onChange={()=>{}}><option value="">Por definir</option>{siteContent.packages.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select><ChevronDown/></label><label className="full">Objetivo<textarea required name="goal" placeholder="¿Qué quieres lograr?"/></label><label className="full">Mensaje<textarea name="message" placeholder="Cuéntanos un poco más"/></label><label className="privacy full"><input type="checkbox" required/> Acepto el tratamiento de mis datos conforme al aviso de privacidad.</label><button className="btn full" disabled={status==="loading"}>{status==="loading"?"Enviando…":status==="success"?"Mensaje recibido":"Solicitar propuesta"}<ArrowRight/></button>{status==="success"&&<p className="success full" role="status">Gracias. Recibimos tus datos y nos pondremos en contacto.</p>}</form></div></section>}
function Footer(){return <footer><div className="container"><div><Logo light/><p>Algoritmos y estética iterando el futuro de tu marca.</p></div><div className="footer-links">{siteContent.nav.map(([l,h])=><a href={h} key={h}>{l}</a>)}</div><div><a href="#">Instagram</a><a href="#">Facebook</a><a href={primaryWhatsApp}>WhatsApp</a></div></div><div className="container legal"><span>© {new Date().getFullYear()} AdFer Marketing</span><a href="#">Aviso de privacidad</a><a href="#">Términos</a></div></footer>}
export default function AdferLanding(){const [pkg,setPkg]=useState<PackageId|"">("");const [showWa,setShowWa]=useState(false);useEffect(()=>{const fn=()=>setShowWa(scrollY>300);addEventListener("scroll",fn,{passive:true});return()=>removeEventListener("scroll",fn)},[]);const choose=(id:PackageId)=>{setPkg(id);track(`${id}_package_click` as "basic_package_click");setTimeout(()=>document.querySelector("#contacto")?.scrollIntoView({behavior:"smooth"}),50)};return <><Header/><main><Hero/><Marquee/><Manifesto/><Services/><Process/><CaseStudy/><Pricing onSelect={choose}/><FAQ/><FinalCTA/><Contact pkg={pkg}/></main><Footer/><AnimatePresence>{showWa&&<motion.a className="wa-float" href={primaryWhatsApp} aria-label="Hablemos de tu proyecto por WhatsApp" title="Hablemos de tu proyecto" initial={{scale:0,opacity:0}} animate={{scale:1,opacity:1}} exit={{scale:0,opacity:0}} onClick={()=>track("whatsapp_click")}><MessageCircle/></motion.a>}</AnimatePresence></>}
